export const APP_ROUTE = {
  ERROR: "/*",
  HOME: "/",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  SEARCH: "/search",
  ABOUT: "/about",
  APARTMENT: "/apartment",
  HOTEL: "hotel",
  DETAIL: "/apartment/:id",
  MOTEL: "motel",
  MOTEL_DETAIL: "/apartment/motel/:id",
  HOME_STAY: "homestay",
  HOME_STAY_DETAIL: "/apartment/homestay/:id",
  CHECKOUT: "/checkout",
  PROFILE: "/profile",
  PROFILE_ORDER: "/orders",
  PROFILE_HOST: "/host",
  PROFILE_CHANGE_PASSWORD: "/change-password",
  FAVOURITES: "/favourites",
  BLOG: "/blog",
  BLOG_DETAIL: "/blog/:id",
  MY_BLOG: "/my-blog",
  CONTACT: "/contact",
  NEWS: "/news",
};
