export const APP_ROUTE = {
  HOME: "/home",
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  SEARCH: "/search",
  APARTMENT: "/apartment",
  HOTEL: "/apartment/hotel",
  HOTEL_DETAIL: "/apartment/hotel/:id",
  MOTEL: "/apartment/motel",
  MOTEL_DETAIL: "/apartment/motel/:id",
  HOME_STAY: "/apartment/homestay",
  HOME_STAY_DETAIL: "/apartment/homestay/:id",
  CHECKOUT: "/checkout",
  PROFILE: "/profile",
  PROFILE_ORDER: "/profile/orders",
  FAVOURITES: "/profile/favourites",
};
